spring:
  application:
    name: movie-service-parcial
  config:
    import: configserver:http://localhost:8888

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

queue:
  movie:
    name: NewMovie
