server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: movie-service
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  zipkin:
    base-url: http://localhost:9411/
    enabled: true        
message: hello from movie-service

management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

