server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: movie-service
  datasource:
    url: jdbc:mysql://localhost:3306/movie-dev
    driverClassName: com.mysql.cj.jdbc.Driver
    username: sa
    password: sa
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

message: hello from movie-service

management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

